project:
  type: book
  output-dir: docs

book:
  title: "Inferência Estatística Aplicada à Economia"
  subtitle: "Notas de Aula"
  navbar:
    background: "#818f81"
    logo: figuras/usp.png
    search: true
    left:
      - text: "Home"
        file: index.qmd
      #- intro.qmd
      #- summary.qmd
      #- pesquisa.qmd
      #- interpretando.qmd
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    background: "#F4F6F6"
    search: true
    style: "docked"
  page-navigation: true
  author:
  - name: "Alexandre Nicolella"
    affiliation: "Unversidade de São Paulo (USP)"
  date: "03/13/2026"
  chapters:
      - index.qmd
      #- intro.qmd
      - cap/cap1_autores.qmd
      - cap/cap2_summary.qmd
      #- cap3_int_R.qmd
      #- cap4_googledrive.qmd
      #- cap5_int_estatistica.qmd
      - cap/cap6_va_bidimensional.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    fontsize: 16px
    #linestretch: 1.7
  #pdf:
    #documentclass: scrreprt


editor: visual

