---
title: "Variáveis Aleatórias Multidimensionais "
subtitle: "Associação entre Variáveis Aleatórias"
format: 
  revealjs:
    menu: true
    theme: serif
    highlight: zenburn
    incremental: false
    center: true
    slide-number: c/t
    width: 1200
    height: 800
    controlsLayout: edges
    controls: true
    progress: true
    history: true
    mouseWheel: true
    transition: 'slide'
    hash: true
    scrollable: true
    mathjax: true
    mathjax-config: TeX-AMS-MML_HTMLorMML
    embed-resources: true
author:
  - name: Alexandre Nicolella
    orcid: 0000-0002-1006-6527
    email: nicolella@usp.br
    affiliations: FEARP/USP
date: last-modified
---



# Covariância e Coeficiente de Correlação {background-color="#87806b"}

# Coeficiente de Correlação {background-color="#4c6073"}
## Definindo 📖

- Até o momento medimos a $E(X)$ e a $Var(X)$, ou seja, uma medida de posição e de variabilidade em relação a $R_x$, 

- Quando temos um vetor bidimensional $(X,Y)$ uma outra medida surge, o "grau de associação" linear entre $X$ e $Y$.


::: {.callout-note icon="false" title="DEFINIÇÃO"}
Seja $(X,Y)$ uma variável aleatória bidimensional. O **Coeficiente de Correlação** $\rho_{X,Y}$ entre $X$ e $Y$ será:

$$
\begin{array}{ccc}
\rho_{X,Y}=\frac{E[(X-E(X))(Y-E(Y))]}{\sqrt{Var(X)Var(Y)}}
\end{array}
$$
:::

# A Covariância {background-color="#4c6073"}
## Definindo 📖

- Um termo muito importante surge na expressão acima, a **Covariância**. 

- Ela mede a variabilidade conjunta de uma variável aleátoria multidimensional.


::: {.callout-note icon="false" title="DEFINIÇÃO"}
A **Covariância** entre $X$ e $Y$, $Cov(X,Y)$, é dada por:
$$
\begin{array}{ccc}
Cov(X,Y)=E[(X-E(X))(Y-E(Y))]
\end{array}
$$
:::

- Para tirar o efeito das escalas de medidas, dividimos pelos desvio-padrões. 


# Propriedades do Coef. de Correlação {background-color="#4c6073"}

## Definindo 📖

- Novamente, a correlação mede o **GRAU DE ASSOCIAÇÃO LINEAR**. 

- Vejamos algumas Propriedades da Correlação:

::: {.callout-note icon="false" title="TEOREMA"} 
O coeficiente de correlação $\rho_{X,Y}$ entre $X$ e $Y$ pode ser apresentado como:
$$
\begin{array}{ccc}
\rho_{X,Y}=\frac{E(XY)-E(X)E(Y)}{\sqrt{Var(X)Var(Y)}}
\end{array}
$$

:::

## Definindo 📖

::: {.callout-note icon="false" title="TEOREMA"} 

**Prova:**
$$
\begin{array}{ccc}
E[(X-E(X))(Y-E(Y))]\\
\\
=E[XY-XE(Y)-E(X)Y+E(X)E(Y)] \\
\\
= E(XY)-E(X)E(Y)-E(X)E(Y)+E(X)E(Y)\\
\\
= E(XY)-E(X)E(Y)
\end{array}
$$
:::

## Independência e a Correlação
  
::: {.callout-note icon="false" title="TEOREMA"}
Se $X$ e $Y$ forem independentes então:
$$
\begin{array}{ccc}
\rho_{X,Y}=0
\end{array}
$$

---

**Prova:**


Da propriedade da independência, se $X$ e $Y$ forem independentes então:
$$
\begin{array}{ccc}
E(X,Y)=E(X)E(Y)
\end{array}
$$
:::

Considerando o teorema acima, e sabendo que as variáveis são independentes, então $\rho_{X,Y}=0$


## Importante: 

- Note que Independência $\Rightarrow \rho_{X,Y}=0$ 

- Mas **não** é verdade que $\rho_{X,Y}=0 \Rightarrow Independência$


## O Intervalo da Correlação

::: {.callout-note icon="false" title="TEOREMA"}
O Coeficiente de Correlação possui valores entre -1 e 1, ou seja:
$$
\begin{array}{ccc}
-1 \leq \rho \leq 1
\end{array}
$$ 

---

**Prova:**

Considere a seguinte desigualdade verdadeira:
$$
\begin{array}{ccc}
(\frac{x-\mu_x}{\sigma_x}\mp \frac{Y-\mu_y}{\sigma_y} )^{2}\geq 0
\end{array}
$$

A expressão continua verdadeira se aplicarmos o operador esperança:

$$
\begin{array}{ccc}
E(\frac{x-\mu_x}{\sigma_x}\mp \frac{Y-\mu_y}{\sigma_y} )^{2}\geq 0
\end{array}
$$

:::

## O Intervalo da Correlação

::: {.callout-note icon="false" title="TEOREMA"}

**Continuação Prova:**

Desenvolvendo, temos que:
$$
\begin{array}{ccc}
E[(\frac{x-\mu_x}{\sigma_x})^{2}+(\frac{Y-\mu_y}{\sigma_y})^{2} \mp 2 (\frac{x-\mu_x}{\sigma_x})(\frac{Y-\mu_y}{\sigma_y}) ]\geq 0
\end{array}
$$

$$
\begin{array}{ccc}
\frac{1}{\sigma_x^{2}}E({X-\mu_x})^{2}+\frac{1}{\sigma_y^{2}}E({Y-\mu_y})^{2}\mp 2 \frac{1}{\sigma_x \sigma_y}E((X-\mu_x)(Y-\mu_y) )\geq 0
\end{array}
$$

$$
\begin{array}{ccc}
\frac{\sigma_x^{2}}{\sigma_x^{2}}+\frac{\sigma_y^{2}}{\sigma_y^{2}}\mp 2\rho \geq 0
\end{array}
$$

$$\begin{array}{ccc}
\mp 2\rho \geq -2
\end{array}
$$

$$
\begin{array}{ccc}
\therefore \rho \geq -1 \ e \ \rho \leq 1
\end{array}
$$

:::


## Correlação: Associação linear

::: {.callout-note icon="false" title="TEOREMA"}
Se X e Y forem duas variáveis aleatórias, onde $Y=AX+B$, onde A e B são constantes. Então $\rho^{2}=1$. Se $A>0$, $\rho=1$. Se $A<0$, $\rho=-1$

---

**Prova:**

$$
\begin{array}{ccc}
Y= AX +B
\\
E(Y)=A E(X)+ B \ e \ VAR(Y)=A^{2}VAR(X)
\\
E(XY)=E(AX^{2}+BX) \ \rightarrow AE(X^{2})+BE(X)
\end{array}
$$

Então: 
$$
\begin{array}{ccc}
\rho^{2}=\frac{A^{2}{Var(X)}}{A^{2}{Var(X)}}=1
\end{array}
$$

:::

## O Coeficiente de Correlação

- Assim, com base no exposto, temos que o coeficiente de correlação é uma medida do grau de linearidade entre X e Y. 

- Dessa forma, $\rho$ próximo a 1 e -1 indicam alto grau de linearidade e $\rho$ próximo a zero indica ausência de relação linear - mas não diz nada sobre relações não-lineares. 

# Correlação: Graficamente {background-color="#4c6073"}

## Simulando as Variáveis e Visualizando

```{r echo = FALSE, fig.cap= "Gráfico de correlação para variáveis simuladas v1 a v5",fig.height = 5, fig.width = 5, fig.align = "center"}
library(psych)
data <- data.frame( var1 = 1:100 + rnorm(100,sd=20), v2 = 1:100 + rnorm(100,sd=27), v3 = rep(1, 100) + rnorm(100, sd = 1)) 
data$v4 = data$var1 ** 2 
data$v5 = -(data$var1 ** 2) 
pairs.panels(data)
```


## Correlação
- Vamos começar pelas variáveis v5 e v4, elas tem um comportantamento conjunto totalmente linear, ou seja, saber de v4 te informa corretmente o que acontecerá com v5. Aqui quando v5 sobe, v4 desce.

- Vejamos agora as variáveis v3 e v2, observe como os dados estão disperso, sem nenhum padrão de comportamento linear. Nesse caso a correlação é próxima a zero (-0.0135). 

## Correlação: Visualização gráfica

- Perceba que a relação não-linear entre v1 e v4 e v1 e v5, faz com que a correlação seja menor que 1 e não perfeita. 

- Já as variáveis v1 e v2 mostram comportamento conjunto positivo, mas não perfeito, reativamente disperso. Quando v1 sobe, v2 também sobe, entretanto não cosneguimos prever esse comportamento perfeitamente. 

